# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  push:
    branches:
      - master
    paths:
      - 'packages/*/package.json'
      - '.github/workflows/publish.yml'

jobs:
  replace-package-json-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: |
          npm i pnpm -g
          pnpm i --no-frozen-lockfile
      - name: publish
        run: npm run pub:only | tee log.txt
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: emit log
        if: always()
        run: ./emit-log.sh
        env:
          DING_TOKEN: ${{secrets.DING_TOKEN}}
